apiVersion: v1
kind: ReplicationController
metadata:
  name: pacer-rc
  labels:
    heritage: helm
spec:
  replicas: 1
  selector:
    app: pacer-app
  template:
    metadata:
      labels:
        app: pacer-app
    spec:
      containers:
      - name: pacer
        image: app-docker136.hex.tno.nl:443/msaas-nld/pacer:po
        command: [ "/root/lrc/launch.sh", "-f Pacer" ]
        env:
        - name: ADVERTISED_ADDRESS
          value: "app-docker13.hex.tno.nl:443"
        - name: PORTICO_UNIQUEFEDERATENAMES
          value: "false"
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        imagePullPolicy: Always
