apiVersion: v1
kind: ReplicationController
metadata:
  name: shipsim-rc
  labels:
    heritage: helm
spec:
  replicas: 1
  selector:
    app: shipsim-app
  template:
    metadata:
      labels:
        app: shipsim-app
    spec:
      containers:
      - name: shipsim
        image: app-docker136.hex.tno.nl:443/msaas-aus/shipsim:po
        command: [ "/root/lrc/launch.sh", "-f Shipsim" ]
        env:
        - name: PORTICO_UNIQUEFEDERATENAMES
          value: "false"
        imagePullPolicy: Always
