apiVersion: v1
kind: Service
metadata:
  name: xserver-sv
  labels:
    heritage: helm
spec:
  selector:
    app: xserver-app
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30000
    protocol: TCP
  - name: x11
    port: 6000
    targetPort: 6000
    protocol: TCP
 