apiVersion: v1
kind: ReplicationController
metadata:
  name: xserver-rc
  labels:
    heritage: helm
spec:
  replicas: 1
  selector:
    app: xserver-app
  template:
    metadata:
      labels:
        app: xserver-app
    spec:
      containers:
      - name: xserver
        image: app-docker136.hex.tno.nl:443/library/xserver
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        - containerPort: 6000
          protocol: TCP
          name: x11
