apiVersion: v1
kind: Service
metadata:
  name: xserverapp
spec:
  selector:
    app: xserverapp
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30000
    protocol: TCP

 