apiVersion: v1
kind: ReplicationController
metadata:
  name: vesselsim
  labels:
    heritage: helm
spec:
  replicas: 1
  selector:
    app: vesselsim-app
  template:
    metadata:
      labels:
        app: vesselsim-app
    spec:
      containers:
      - name: start
        image: app-docker136.hex.tno.nl:443/msaas-nld/start:po
        env:
        - name: DISPLAY
          value: xserver-sv.default.svc.cluster.local:0
      - name: shipsim
        image: app-docker136.hex.tno.nl:443/msaas-aus/shipsim:po
        command: [ "/root/lrc/launch.sh", "-f Shipsim" ]
        env:
        - name: MINSLEEP
          value: "15"
      - name: kml
        image: app-docker136.hex.tno.nl:443/msaas-nld/kmlserver:po
        command: [ "/root/lrc/launch.sh", "-f KMLServer -iconurl http://app-docker11.hex.tno.nl:30001" ]
        env:
        - name: MINSLEEP
          value: "10"
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
