apiVersion: v1
kind: Service
metadata:
  name: vesselsim-sv
  labels:
    heritage: helm
spec:
  selector:
    app: vesselsim-app
  type: NodePort
  ports:
  - name: kml
    port: kml
    nodePort: 30001
    protocol: TCP
  - name: pacer
    port: pacer
    nodePort: 30002
    protocol: TCP
