apiVersion: v1
kind: Service
metadata:
  name: pacer-sv
  labels:
    heritage: helm
spec:
  selector:
    app: pacer-app
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30010
    protocol: TCP
