apiVersion: v1
kind: ReplicationController
metadata:
  name: kmlserver-rc
  labels:
    heritage: helm
spec:
  replicas: 1
  selector:
    app: kmlserver-app
  template:
    metadata:
      labels:
        app: kmlserver-app
    spec:
      containers:
      - name: start
        image: app-docker136.hex.tno.nl:443/msaas-nld/start:po
        command: [ "/root/lrc/launch.sh", "-f start -d allfoms -p 8990" ]
        env:
        - name: DISPLAY
          value: xserver-sv.default.svc.cluster.local:0
        - name: PORTICO_UNIQUEFEDERATENAMES
          value: "false"
        imagePullPolicy: Always
      - name: kml
        image: app-docker136.hex.tno.nl:443/msaas-nld/kmlserver:po
        command: [ "/root/lrc/launch.sh", "-f KMLServer -c pitch-logicaltime.config -iconurl http://app-docker13.hex.tno.nl:443/kmlserver/entities" ]
        env:
        - name: LRC_MASTERHOST
          value: "127.0.0.1"
        - name: LRC_MASTERPORT
          value: "8990"
        - name: PORTICO_UNIQUEFEDERATENAMES
          value: "false"
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        imagePullPolicy: Always
